Fix root_gpu crash with pytorch-lightning >= 1.8
AttributeError: `Trainer.root_gpu` was deprecated in
v1.6 and is no longer accessible as of v1.8. Please use
`Trainer.strategy.root_device.index` instead.

Support for Trainer.root_gpu was removed in:
https://github.com/Lightning-AI/lightning/issues/11994